"""Keep the docs in step with the code, using the graphify knowledge graph.

Reads ``graphify-out/graph.json`` and:

1. writes ``docs/calc/reference/generated/components.md``: a map of the modules of
   ``pylibs-calc`` and its plugin packages (``pylibs-calc-whatif``), their public classes and
   functions, what depends on what and which components are used most;
2. finds hand-written pages that may be out of date. A page lists the source files it explains
   in its front matter (``covers:``). When the public surface of one of those files changes in
   the graph (symbols added or removed, docstrings changed, calls to other modules changed),
   the page is listed in ``docs/calc/reference/generated/stale.md`` and gets a warning banner on
   the site until someone reviews it and runs ``--ack``;
3. lists public names (``__all__`` of each package) that no page mentions.

Only code nodes under ``packages/*/src`` are used, so documentation nodes in the graph never feed
back into the output. The output has no timestamps: the same graph always gives the same files.

    python scripts/docs_from_graph.py              # regenerate
    python scripts/docs_from_graph.py --check      # exit 1 if the generated files are out of date
    python scripts/docs_from_graph.py --ack PAGE   # mark a page (path under docs/) as reviewed
    python scripts/docs_from_graph.py --ack-all    # mark every page as reviewed
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import re
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
GRAPH = ROOT / "graphify-out" / "graph.json"
DOCS = ROOT / "docs"
STATE = DOCS / ".docs-sync.json"
PACKAGE = "calc"
# The core package first, then its plugin packages; each maps its source root to its import name.
SOURCES = {
    f"packages/{PACKAGE}/src/pylibs_{PACKAGE}/": f"pylibs_{PACKAGE}",
    f"packages/{PACKAGE}_whatif/src/pylibs_{PACKAGE}_whatif/": f"pylibs_{PACKAGE}_whatif",
}
SRC = next(iter(SOURCES))
GENERATED = DOCS / PACKAGE / "reference" / "generated"
COMPONENTS = GENERATED / "components.md"
STALE = GENERATED / "stale.md"
REPO_URL = "https://github.com/sanjaysharmagwl/py-libs/blob/master/"
HEADER = (
    "<!-- Generated by scripts/docs_from_graph.py from graphify-out/graph.json. "
    "Do not edit by hand: run `make docs-sync`. -->\n"
)
# Relations that make up a file's public surface for stale detection.
SURFACE = ("contains", "method", "inherits", "calls", "imports_from")


# --- Reading the graph ---------------------------------------------------------------------


@dataclass
class Symbol:
    id: str
    name: str
    kind: str  # "class", "function" or "method"
    file: str
    line: int
    doc: str = ""
    methods: list[str] = field(default_factory=list)


@dataclass
class Module:
    id: str
    file: str
    doc: str = ""
    symbols: list[Symbol] = field(default_factory=list)
    imports: set[str] = field(default_factory=set)  # other module files in the package
    external: set[str] = field(default_factory=set)  # third-party top-level packages


@dataclass
class Graph:
    commit: str
    modules: dict[str, Module]  # by file
    nodes: dict[str, dict[str, Any]]
    links: list[dict[str, Any]]
    module_of: dict[str, str]  # node id -> file, for code nodes in the package

    def symbol(self, node_id: str) -> Symbol | None:
        file = self.module_of.get(node_id)
        if file is None:
            return None
        return next((s for s in self.modules[file].symbols if s.id == node_id), None)


def load_graph(path: Path = GRAPH) -> Graph:
    raw = json.loads(path.read_text())
    nodes = {n["id"]: n for n in raw["nodes"]}
    links = raw["links"]

    def in_package(node: dict[str, Any]) -> bool:
        return node.get("file_type") == "code" and source_root(str(node.get("source_file", "")))

    modules: dict[str, Module] = {}
    for node in nodes.values():
        if (
            in_package(node)
            and node["label"].endswith(".py")
            and node.get("source_location") == "L1"
        ):
            modules[node["source_file"]] = Module(node["id"], node["source_file"])
    module_ids = {m.id: m.file for m in modules.values()}

    methods = {e["target"] for e in links if e["relation"] == "method"}
    symbols: dict[str, Symbol] = {}
    for node in nodes.values():
        if not in_package(node) or node["id"] in module_ids or not node.get("_callable"):
            continue
        name = node["label"].removeprefix(".").removesuffix("()")
        kind = (
            "class"
            if node.get("_callable_class")
            else "method"
            if node["id"] in methods
            else "function"
        )
        symbols[node["id"]] = Symbol(
            node["id"], name, kind, node["source_file"], _line(node.get("source_location"))
        )

    # Docstrings are "rationale" nodes on the line after the definition they describe.
    docs_at = {
        (n["source_file"], _line(n.get("source_location"))): n["label"]
        for n in nodes.values()
        if n.get("file_type") == "rationale" and source_root(str(n.get("source_file", "")))
    }
    for sym in symbols.values():
        sym.doc = docs_at.get((sym.file, sym.line + 1), "")
    for mod in modules.values():
        mod.doc = docs_at.get((mod.file, 1), "")

    for edge in links:
        rel, src, dst = edge["relation"], edge["source"], edge["target"]
        if rel == "method" and src in symbols and dst in symbols:
            symbols[src].methods.append(symbols[dst].name)
        elif rel == "imports_from" and src in module_ids:
            mod = modules[module_ids[src]]
            if dst in module_ids and module_ids[dst] != mod.file:
                mod.imports.add(module_ids[dst])

    for mod in modules.values():
        mod.external = third_party_imports(ROOT / mod.file)
    for sym in symbols.values():
        if sym.kind != "method":
            modules[sym.file].symbols.append(sym)
    for mod in modules.values():
        mod.symbols.sort(key=lambda s: s.line)
    for sym in symbols.values():
        sym.methods.sort()

    module_of = {**module_ids, **{s.id: s.file for s in symbols.values()}}
    return Graph(raw.get("built_at_commit") or "unknown", modules, nodes, links, module_of)


def source_root(file: str) -> str:
    """The package source root a file belongs to ("" if none)."""
    return next((root for root in SOURCES if file.startswith(root)), "")


def _line(location: str | None) -> int:
    match = re.match(r"L(\d+)", location or "")
    return int(match[1]) if match else 0


def third_party_imports(path: Path) -> set[str]:
    """Top-level third-party packages a file imports.

    Read from the source rather than the graph, whose ids for external modules are not stable.
    """
    if not path.is_file():
        return set()
    found = set()
    for node in ast.walk(ast.parse(path.read_text())):
        if isinstance(node, ast.Import):
            found |= {alias.name.split(".")[0] for alias in node.names}
        elif isinstance(node, ast.ImportFrom) and node.level == 0 and node.module:
            found.add(node.module.split(".")[0])
    return {
        name
        for name in found
        if name not in sys.stdlib_module_names
        and name != "__future__"
        and not name.startswith("pylibs_")
    }


# --- The component map ---------------------------------------------------------------------


def group_of(file: str) -> str:
    """``compile/query.py`` -> ``compile``; ``engine.py`` -> ``engine``; a plugin package is one
    group, e.g. ``plugin_whatif``."""
    root = source_root(file)
    if root != SRC:
        return "plugin_" + SOURCES[root].removeprefix(f"pylibs_{PACKAGE}_")
    rel = file.removeprefix(SRC)
    head = rel.split("/")[0]
    return head.removesuffix(".py") if head != "__init__.py" else "__init__"


def module_name(file: str) -> str:
    root = source_root(file)
    rel = file.removeprefix(root).removesuffix(".py").replace("/", ".")
    name = f"{SOURCES[root]}.{rel}".removesuffix(".__init__")
    return name


def hubs(graph: Graph, limit: int = 12) -> list[tuple[Symbol, int]]:
    """Symbols used from the most other source files (tests included, as real callers)."""
    users: dict[str, set[str]] = defaultdict(set)
    for edge in graph.links:
        if edge["relation"] not in ("calls", "references", "uses", "inherits"):
            continue
        target = edge["target"]
        sym = graph.symbol(target)
        caller = edge.get("source_file") or ""
        if sym is not None and caller and caller != sym.file:
            users[target].add(caller)
    ranked = sorted(users.items(), key=lambda kv: (-len(kv[1]), graph.nodes[kv[0]]["label"]))
    out = []
    for node_id, callers in ranked[:limit]:
        sym = graph.symbol(node_id)
        if sym is not None:
            out.append((sym, len(callers)))
    return out


def render_components(graph: Graph) -> str:
    modules = sorted(graph.modules.values(), key=lambda m: m.file)
    groups = sorted({group_of(m.file) for m in modules})
    edges: Counter[tuple[str, str]] = Counter()
    for mod in modules:
        for dep in mod.imports:
            a, b = group_of(mod.file), group_of(dep)
            if a != b and "__init__" not in (a, b):
                edges[(a, b)] += 1

    out = [
        HEADER,
        "# Components",
        "",
        "A map of `pylibs-calc` and its plugin packages (`plugin_*`, e.g. `pylibs-calc-whatif`), "
        "generated from the code knowledge graph (graphify), built at "
        f"commit `{graph.commit[:12]}`. It lists every module with its public classes and "
        "functions, what each part imports and which components the rest of the code relies on "
        "most. For how the parts work together, read "
        "[Architecture](../../concepts/architecture.md).",
        "",
        "## How the parts depend on each other",
        "",
        "An arrow `A --> B` means code in `A` imports from `B`. Foundations, the parts that most "
        "others import, are shown on their own without arrows to keep the picture readable.",
        "",
        "```mermaid",
        "flowchart TB",
    ]
    parts = [g for g in groups if g != "__init__"]
    importers: dict[str, set[str]] = defaultdict(set)
    for a, b in edges:
        importers[b].add(a)
    foundations = sorted(g for g in parts if len(importers[g]) * 2 >= len(parts) - 1)
    out.append('  subgraph foundations["Foundations: imported by most parts"]')
    out += [f"    {g}[{g}]" for g in foundations]
    out.append("  end")
    for g in parts:
        if g not in foundations:
            out.append(f"  {g}[{g}]")
    for (a, b), _count in sorted(edges.items()):
        if b not in foundations and a not in foundations:
            out.append(f"  {a} --> {b}")
    out += ["```", ""]

    out += [
        "## Most used components",
        "",
        "Ranked by how many other source files (tests included) call, reference or subclass them.",
        "",
        "| Component | Kind | Module | Used from files |",
        "| --- | --- | --- | --- |",
    ]
    for sym, count in hubs(graph):
        out.append(
            f"| [`{sym.name}`]({REPO_URL}{sym.file}#L{sym.line}) | {sym.kind} | "
            f"`{module_name(sym.file)}` | {count} |"
        )
    out.append("")

    externals = sorted({e for m in modules for e in m.external})
    out += ["## Third-party dependencies by part", "", "| Part | Imports |", "| --- | --- |"]
    by_group: dict[str, set[str]] = defaultdict(set)
    for mod in modules:
        by_group[group_of(mod.file)] |= mod.external
    for g in groups:
        libs = ", ".join(f"`{e}`" for e in sorted(by_group[g])) or "—"
        out.append(f"| `{g}` | {libs} |")
    out += ["", f"All third-party imports: {', '.join(f'`{e}`' for e in externals)}.", ""]

    out += ["## Modules", ""]
    for mod in modules:
        out.append(f"### `{module_name(mod.file)}`")
        out.append("")
        if mod.doc:
            out.append(_clean(mod.doc))
            out.append("")
        out.append(f"Source: [`{mod.file}`]({REPO_URL}{mod.file})")
        out.append("")
        public = [s for s in mod.symbols if not s.name.startswith("_")]
        if public:
            out += ["| Name | Kind | Summary |", "| --- | --- | --- |"]
            for sym in public:
                methods = [m for m in sym.methods if not m.startswith("_")]
                extra = f" Methods: {', '.join(f'`{m}`' for m in methods)}." if methods else ""
                summary = (_clean(sym.doc) + extra).strip() or "—"
                out.append(
                    f"| [`{sym.name}`]({REPO_URL}{sym.file}#L{sym.line}) | {sym.kind} | {summary} |"
                )
            out.append("")
        deps = sorted(module_name(d) for d in mod.imports)
        if deps:
            out.append("Imports: " + ", ".join(f"`{d}`" for d in deps))
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def _code(text: str) -> str:
    """Text for an inline code span (which can't contain backticks)."""
    return _clean(text).replace("`", "'")


def _clean(text: str) -> str:
    text = " ".join(text.split()).replace("|", "\\|")
    return text.replace("``", "`")


# --- Stale pages ---------------------------------------------------------------------------


def surface(graph: Graph, file: str) -> list[str]:
    """The public surface of one source file, as sorted lines that are easy to diff.

    Line numbers are left out, so moving or reformatting code changes nothing.
    """
    mod = graph.modules.get(file)
    if mod is None:
        return []
    lines = []
    if mod.doc:
        lines.append(f"module doc: {mod.doc}")
    for sym in mod.symbols:
        if sym.name.startswith("_"):
            continue
        lines.append(f"{sym.kind} {sym.name}" + (f": {sym.doc}" if sym.doc else ""))
        lines += [f"{sym.kind} {sym.name}.{m}" for m in sym.methods if not m.startswith("_")]
    ids = {mod.id, *(s.id for s in mod.symbols)}
    for edge in graph.links:
        if edge["relation"] in ("calls", "imports_from", "inherits") and edge["source"] in ids:
            target = graph.nodes.get(edge["target"], {})
            target_file = str(target.get("source_file", ""))
            if target_file != file:
                lines.append(f"{edge['relation']} {target.get('label', edge['target'])}")
    return sorted(set(lines))


def digest(lines: list[str]) -> str:
    return hashlib.sha256("\n".join(lines).encode()).hexdigest()[:16]


def pages() -> dict[str, list[str]]:
    """Hand-written pages (path under docs/) and the source files their front matter covers."""
    out = {}
    for path in sorted(DOCS.rglob("*.md")):
        if GENERATED in path.parents:
            continue
        covers = front_matter_list(path.read_text(), "covers")
        if covers:
            out[path.relative_to(DOCS).as_posix()] = covers
    return out


def front_matter_list(text: str, key: str) -> list[str]:
    """Read a ``key:`` list from YAML front matter (only the simple ``- item`` form)."""
    if not text.startswith("---\n"):
        return []
    end = text.find("\n---", 4)
    if end < 0:
        return []
    items: list[str] = []
    active = False
    for line in text[4:end].splitlines():
        if re.match(rf"^{key}:\s*$", line):
            active = True
        elif active and (m := re.match(r"^\s+-\s+(.+?)\s*$", line)):
            items.append(m[1].strip("'\""))
        elif active and line.strip():
            active = False
    return items


def load_state() -> dict[str, Any]:
    if STATE.is_file():
        state: dict[str, Any] = json.loads(STATE.read_text())
        return state
    return {"pages": {}}


def save_state(state: dict[str, Any]) -> None:
    STATE.write_text(json.dumps(state, indent=2, sort_keys=True) + "\n")


@dataclass
class Stale:
    page: str
    file: str
    added: list[str]
    removed: list[str]
    reason: str


def find_stale(graph: Graph, state: dict[str, Any] | None = None) -> list[Stale]:
    state = load_state() if state is None else state
    out = []
    for page, covers in pages().items():
        reviewed = state["pages"].get(page)
        for file in covers:
            current = surface(graph, file)
            if not (ROOT / file).is_file():
                out.append(Stale(page, file, [], [], "the covered file no longer exists"))
            elif file not in graph.modules:
                out.append(
                    Stale(page, file, [], [], "the file is not in the graph yet (run `make graph`)")
                )
            elif reviewed is None or file not in reviewed:
                out.append(
                    Stale(page, file, [], [], "never reviewed (run `--ack` after checking it)")
                )
            elif reviewed[file]["digest"] != digest(current):
                before = set(reviewed[file]["surface"])
                out.append(
                    Stale(
                        page,
                        file,
                        sorted(set(current) - before),
                        sorted(before - set(current)),
                        "the code changed since the page was last reviewed",
                    )
                )
    return out


def ack(graph: Graph, targets: list[str]) -> list[str]:
    state = load_state()
    covered = pages()
    unknown = [t for t in targets if t not in covered]
    if unknown:
        raise SystemExit(f"error: no page with a 'covers:' list at {', '.join(unknown)}")
    for page in targets:
        state["pages"][page] = {
            file: {"digest": digest(surface(graph, file)), "surface": surface(graph, file)}
            for file in covered[page]
        }
    # Forget pages that no longer exist.
    state["pages"] = {p: v for p, v in state["pages"].items() if p in covered}
    save_state(state)
    return targets


# --- Coverage ------------------------------------------------------------------------------


def public_names() -> list[str]:
    """``package.Name`` for every name in the ``__all__`` of each package."""
    out = []
    for root, package in SOURCES.items():
        init = ROOT / root / "__init__.py"
        if not init.is_file():
            continue
        for node in ast.parse(init.read_text()).body:
            if isinstance(node, ast.Assign) and any(
                isinstance(t, ast.Name) and t.id == "__all__" for t in node.targets
            ):
                names = ast.literal_eval(node.value)
                out += [f"{package}.{n}" for n in names if not n.startswith("__")]
    return out


def undocumented() -> list[str]:
    text = "\n".join(
        p.read_text()
        for p in DOCS.rglob("*.md")
        if GENERATED not in p.parents and p.name != "api.md"
    )
    return [
        n for n in public_names() if not re.search(rf"\b{re.escape(n.rsplit('.', 1)[1])}\b", text)
    ]


def render_stale(graph: Graph, stale: list[Stale], missing: list[str]) -> str:
    out = [
        HEADER,
        "# Docs freshness",
        "",
        f"Checked against the code graph at commit `{graph.commit[:12]}`.",
        "",
        "Each hand-written page lists the source files it explains in its front matter "
        "(`covers:`). A page shows up here when the public surface of one of those files has "
        "changed since someone last reviewed the page: classes or functions added or removed, "
        "docstrings edited, or different calls to other modules. After checking the page, run "
        "`uv run python scripts/docs_from_graph.py --ack docs/<page>` and commit the result.",
        "",
        "## Pages to review",
        "",
    ]
    if not stale:
        out += ["Every page is up to date with the code. :white_check_mark:", ""]
    for page in sorted({s.page for s in stale}):
        link = "../../../" + page
        out += [f"### [{page}]({link})", ""]
        for s in (s for s in stale if s.page == page):
            out.append(f"- `{s.file}`: {s.reason}")
            for line in s.added[:15]:
                out.append(f"    - added: `{_code(line)}`")
            for line in s.removed[:15]:
                out.append(f"    - removed: `{_code(line)}`")
            hidden = max(0, len(s.added) - 15) + max(0, len(s.removed) - 15)
            if hidden:
                out.append(f"    - … and {hidden} more changes")
        out.append("")
    out += ["## Public names no page mentions", ""]
    if missing:
        out.append(
            "These are exported from `pylibs_calc` or a plugin package but only appear in the "
            "[Python API](../api.md) reference:"
        )
        out.append("")
        out += [f"- `{name}`" for name in missing]
    else:
        out.append(
            "Every exported name (`__all__` of each package) is mentioned on at least one page."
        )
    return "\n".join(out).rstrip() + "\n"


# --- Entry point ---------------------------------------------------------------------------


def generate(graph: Graph) -> dict[Path, str]:
    return {
        COMPONENTS: render_components(graph),
        STALE: render_stale(graph, find_stale(graph), undocumented()),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    parser.add_argument(
        "--ack", nargs="+", metavar="PAGE", help="mark pages (under docs/) reviewed"
    )
    parser.add_argument("--ack-all", action="store_true", help="mark every page reviewed")
    parser.add_argument(
        "--fail-on-stale", action="store_true", help="also fail if any page needs review"
    )
    args = parser.parse_args(argv)

    if not GRAPH.is_file():
        print(f"error: {GRAPH.relative_to(ROOT)} not found; run `make graph`", file=sys.stderr)
        return 1
    graph = load_graph()

    if args.ack or args.ack_all:
        targets = sorted(pages()) if args.ack_all else [a.removeprefix("docs/") for a in args.ack]
        for page in ack(graph, targets):
            print(f"reviewed: docs/{page}")

    outputs = generate(graph)
    status = 0
    for path, text in outputs.items():
        rel = path.relative_to(ROOT)
        if args.check:
            if not path.is_file() or path.read_text() != text:
                print(f"out of date: {rel} (run `make docs-sync`)", file=sys.stderr)
                status = 1
        elif not path.is_file() or path.read_text() != text:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
            print(f"wrote {rel}")

    stale = find_stale(graph)
    if stale:
        count = len({s.page for s in stale})
        print(f"{count} page(s) may be out of date; see {STALE.relative_to(ROOT)}")
        if args.fail_on_stale:
            status = 1
    return status


if __name__ == "__main__":
    raise SystemExit(main())
